WIP: Front page fed
poldracklab/crn_app pull request #149
Opened 2016-10-17 16:20 UTC by thinknoack

2016-10-17 19:19 UTC, constellates requested changes
Aside from the inline comments we should rename the user directory to something like "landing" or "intro" or "frontpage" and rename the user components to match.

Also make sure to run the linter and fix any related issues.

2016-10-17 19:19 UTC, constellates commented on src/scripts/common/partials/browsePipelines.jsx
> +// dependencies -------------------------------------------------------
I'm not sure this needs to be it's own component and if it does I don't think I'd put it in /common/partials. /common should be for stuff that get reused in multiple parts of the app.

2016-10-17 19:19 UTC, constellates commented on src/scripts/common/partials/footer.jsx
> +// dependencies -------------------------------------------------------
If this does get used throughout it's fine in partials otherwise if it ends up only on the landing page we should move it into that directory.

2016-10-17 19:19 UTC, constellates commented on src/scripts/common/partials/footer.jsx
> +        let isLoggedIn    = !!this.state.token;
Because they're always used together we could simplify this 

```
let isLoggedIn    = !!this.state.token;
let loading       = this.state.loading;
```

to

```
let showSignOut = !!this.state.token && !this.state.loading;
```

2016-10-17 19:19 UTC, constellates commented on src/scripts/common/partials/footer.jsx
> +                            <li> {isLoggedIn && !loading ? <a onClick={this._signOut}>Sign Out</a> : <a onClick={userStore.signIn.bind(null)} >Sign in</a>}</li>
Then This would become

```
<li>{showSignOut ? <a onClick={this._signOut}>Sign Out</a> : <a onClick={userStore.signIn.bind(null)} >Sign in</a>}</li>
```

2016-10-17 19:19 UTC, constellates commented on src/scripts/common/partials/frontPageTabs.jsx
> +// life cycle events --------------------------------------------------
Add a return before and after this comment line.

2016-10-17 19:19 UTC, constellates commented on src/scripts/common/partials/frontPageTabs.jsx
> +        let firstHeader, firstDescription, firstImage, secondHeader, secondDescription, secondImage;
I would move the logic starting here and ending around line 127 to a separate function that return the tab content.

2016-10-17 19:19 UTC, constellates commented on src/scripts/common/partials/frontPageTabs.jsx
> +                {this.state.currentTab != 0 ? tabcontent : null}
This logic can be moved into the new function mentioned above. So the function can first check if the current tab is 0 and then return false otherwise it can continue to the rest of the logic. This will allow this line to be simplified to.

```
{this._tabContent(this.state.currentTab)}
```

2016-10-17 19:19 UTC, constellates commented on src/scripts/common/partials/frontPageTabs.jsx
> +
Add a line comment between the render method and the start of custom methods.

```
// custom methods -------------------------------------------------------
```

2016-10-17 19:19 UTC, constellates commented on src/scripts/user/frontPage.jsx
> +        let form;
I would move each variable between here and 108 into individual template functions to keep the render method clean.

2016-10-18 15:58 UTC, thinknoack commented on src/scripts/common/partials/footer.jsx
> +// dependencies -------------------------------------------------------
leaving for now

2016-10-18 15:59 UTC, thinknoack commented on src/scripts/common/partials/browsePipelines.jsx
> +// dependencies -------------------------------------------------------
moved

2016-10-18 16:00 UTC, thinknoack commented on src/scripts/common/partials/footer.jsx
> +        let isLoggedIn    = !!this.state.token;
done

2016-10-18 16:00 UTC, thinknoack commented on src/scripts/common/partials/footer.jsx
> +                            <li> {isLoggedIn && !loading ? <a onClick={this._signOut}>Sign Out</a> : <a onClick={userStore.signIn.bind(null)} >Sign in</a>}</li>
done

2016-10-18 16:01 UTC, thinknoack commented on src/scripts/common/partials/frontPageTabs.jsx
> +// life cycle events --------------------------------------------------
done

2016-10-18 16:12 UTC, thinknoack commented on src/scripts/common/partials/frontPageTabs.jsx
> +                {this.state.currentTab != 0 ? tabcontent : null}
done

2016-10-18 16:55 UTC, thinknoack commented on src/scripts/user/frontPage.jsx
> +        let form;
done

2016-10-18 16:55 UTC, thinknoack commented on src/scripts/common/partials/frontPageTabs.jsx
> +
done

2016-10-18 19:32 UTC, constellates approved these changes

2016-10-18 19:33 UTC, merged